### ISSUE TITLE
2.0.45 - GUI issues

### ISSUE THREAD

**Issue by bovirus** [Bazzu85/MKVmergeBatcher#10]
@Bazzu85 

GUI issues not fixed

![image](https://user-images.githubusercontent.com/1262554/189318822-20c2cc32-2c93-4907-9adb-deba960734ef.png)

![image](https://user-images.githubusercontent.com/1262554/189318905-f63d76d5-2c6c-477d-bc0b-cadfc0b2a957.png)

![image](https://user-images.githubusercontent.com/1262554/189318991-e84aaded-7e70-4e4a-ae3a-3e76f5522c35.png)

**Comment by bovirus** [comment]
@Bazzu85 

![image](https://user-images.githubusercontent.com/1262554/189352786-972a9d05-c1bd-4ad6-90ec-bd707d04b3e9.png)

Please increase About window woidth.,
Currently is too small and the window title "Info programma" is truncated.

**Comment by Bazzu85** [comment]
Hi, I merged your last translation and fixed the graphic glitches.
Can you try this build before pushing to release section?
[MKVmergeBatcher 2.0.46.905.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/9537055/MKVmergeBatcher.2.0.46.905.zip)

**Comment by bovirus** [comment]
@Bazzu85 

Fixed most of the issues about GUI and language.

Jsu a small GUI issue.
Please check screenshot.

![image](https://user-images.githubusercontent.com/1262554/189491397-f36b259c-a1a1-4eba-8966-7bde4eb7afdb.png)

"Visualizza coda" text overlap graphics image

![image](https://user-images.githubusercontent.com/1262554/189493021-f8f5c360-e7b5-4bca-a288-2fb5ea20344b.png)

"Video files" ("File video" in italian) is untranslated.

**Comment by Bazzu85** [comment]
> Jsu a small GUI issue.

Hi, here's: 
[MKVmergeBatcher 2.0.46.906.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/9557214/MKVmergeBatcher.2.0.46.906.zip)

if you confirm I can put it in release section!

**Comment by bovirus** [comment]
@Bazzu85 

Thanks for new version

![image](https://user-images.githubusercontent.com/1262554/189910882-74836b90-656d-43d8-a7ed-6181ac614909.png)

String "json files (*.json)" not translated (in italian is "Files json (*.json)

![image](https://user-images.githubusercontent.com/1262554/189911098-e1f7ad9c-b540-4191-90e3-e29f10519016.png)

![image](https://user-images.githubusercontent.com/1262554/189911412-629bd26c-2852-49fe-8af9-c87f2c395e52.png)

In this window if you can please set two strings with right alignment
See before and after window layout.

![image](https://user-images.githubusercontent.com/1262554/189911459-f5ec85bc-35de-49a2-8d6c-5d70eddce72d.png)

![image](https://user-images.githubusercontent.com/1262554/189911510-0dc92532-7a93-4102-8d2a-dedf2f452d3b.png)

In this window mkvmerge path can be truncated.
Move "Extension" subwindow down, move down mkvmerge box path and "Browse" button.
See before and after window layout.

Thanks.

**Comment by Bazzu85** [comment]
Hi, sorry for the delay

> String "json files (_.json)" not translated (in italian is "Files json (_.json)

done

> In this window if you can please set two strings with right alignment

done

> In this window mkvmerge path can be truncated.

done. You can always enlarge the window!

Try this build: 
[MKVmergeBatcher 2.0.46.910.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/9714003/MKVmergeBatcher.2.0.46.910.zip)

**Comment by bovirus** [comment]
@Bazzu85 

Thanks for new version.

All fixes reported in the apst now are OK.

I found another GUI issues.

![image](https://user-images.githubusercontent.com/1262554/194060847-57c76ce5-bc71-4d5c-b35f-d467c196b910.png)

"exe files (*.exe)" for me should be "Exe files (*.exe)"
In Italian si "File eseguibili (*.exe)"

Thanks.

**Comment by Bazzu85** [comment]
Thx for the report!

I added the translation records for the file types in all sections (bat, video etc).

If you want you can review the translation from this file: 
[2022_10_07_17_49.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/9735377/2022_10_07_17_49.xlsx)

Can you try the last build? 
[MKVmergeBatcher 2.0.46.911.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/9735381/MKVmergeBatcher.2.0.46.911.zip)

**Comment by bovirus** [comment]
@Bazzu85 

![image](https://user-images.githubusercontent.com/1262554/194750975-39a2b1fc-1092-4985-bb5d-c57612b53c77.png)

"exe files" drop down ìtranslation problem fixed.

Please change 

"Indirizzo file video" in "Percorso file video"
"Files video" in "File video"

Thanks.

**Comment by Bazzu85** [comment]
> @Bazzu85
> 
> ![image](https://user-images.githubusercontent.com/1262554/194750975-39a2b1fc-1092-4985-bb5d-c57612b53c77.png)
> 
> "exe files" drop down ìtranslation problem fixed.
> 
> Please change
> 
> "Indirizzo file video" in "Percorso file video" "Files video" in "File video"
> 
> Thanks.

Please update the excel file and re-attach here

**Comment by bovirus** [comment]
@Bazzu85 

How to add new line in multiperiod string like

"Coda in elaborazione. Vuoi stoppare l'attuale job?"

"Coda in elaborazione. 
Vuoi stoppare l'attuale job?"

**Some proposal to help the translator and your job.**

**- Use "?" in affermative strings (like options)**

Not use "?" a the end of string that are not regarding confirm message but only options or menu entry.
Because thd translation is different if is a question or affermative (like options).

**- Use of "position" term**

Not use "position" when you are referring about a path (ex.  for a file).
In this case use path" instread "position".
Because path and position have different context use and translation.
 
Thanks.

[2022_10_07_17_49 (1).xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/9741357/2022_10_07_17_49.1.xlsx)

**Comment by Bazzu85** [comment]
> How to add new line in multiperiod string like
> 
> "Coda in elaborazione. Vuoi stoppare l'attuale job?"
> 
> "Coda in elaborazione. Vuoi stoppare l'attuale job?"

I've to try on a label and see how is transported on the resx file (maybe with a \n ?)

**Comment by bovirus** [comment]
@Bazzu85 

It seems checking here

https://social.msdn.microsoft.com/Forums/vstudio/en-US/701c5440-7f95-4fb7-8e2a-b7cfec2669cc/how-to-write-new-line-character-n-in-resx-file?forum=netfxbcl

that you can use one of these

\n
#13

Please check and when you will have the confirm post the answer here and I will update the Excel files.

**Comment by Bazzu85** [comment]
Hi,

sorry for the long wait but I totally forgot this issue.

Using the IDE I can put multiline text.
Here's an example:

![image](https://user-images.githubusercontent.com/7345587/221838382-11f1bc95-a0d4-4c61-b3f8-77008c803763.png)

is this what you want to achieve?
if yes you can manage multiline translation in excel file directly

![image](https://user-images.githubusercontent.com/7345587/221838991-50df437f-4120-4cc2-b37b-5527721878fa.png)

I'll attach the last version: 
[2023_02_28_12_17.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/10849623/2023_02_28_12_17.xlsx)

**Comment by bovirus** [comment]
@Bazzu85 

Done. Thanks.

[2023_02_28_12_17.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/10850318/2023_02_28_12_17.xlsx)

**Comment by Bazzu85** [comment]
> @Bazzu85
> 
> Done. Thanks.
> 
> [2023_02_28_12_17.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/10850318/2023_02_28_12_17.xlsx)

Hi,
can you try this build?
[MKVmergeBatcher 2.0.46.917.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/10851400/MKVmergeBatcher.2.0.46.917.zip)

**Comment by bovirus** [comment]
Some issues

Please check screenshots

![image](https://user-images.githubusercontent.com/1262554/221896165-94163e5d-64ed-42fd-8b78-cf8d17ff683a.png)

Increment Error window width

![image](https://user-images.githubusercontent.com/1262554/221896328-ac768a73-bf8b-46fd-a789-ff97e5cd865e.png)

Please check overlap on bottom left

Please replace "Attenzione:" with "Avvisi:"

Please check button ballon help on top right (seems swapped - both in english and italian)

**Comment by Bazzu85** [comment]
> Increment Error window width

To show this box the app use the standard MessageBox item. This is not customizable.
A custom form can be done but the effort is too much at the moment. sorry

> Please check overlap on bottom left

Fixed.

> Please replace "Attenzione:" with "Avvisi:"

Nope. The warning/error wording needs to be homogeneous.
In italian translation is "Attenzione" in all sections

![image](https://user-images.githubusercontent.com/7345587/221981637-eb074f59-06a2-4596-bc11-3f417cca5e10.png)

![image](https://user-images.githubusercontent.com/7345587/221981807-be6924a3-74ad-4454-a956-e85acec6064a.png)

![image](https://user-images.githubusercontent.com/7345587/221981858-7dd719fe-8859-4371-a657-35d2ff67242b.png)

if you meant that in the particular section of the windows highlighted previously need to be "Avvisi" you can try to fix the excel section about "WarningLabel" and send it again

> Please check button ballon help on top right (seems swapped - both in english and italian)

This are swaped in italian translation I see:
![image](https://user-images.githubusercontent.com/7345587/221983019-9b814778-4d70-47ce-a7fe-7516d3133eb2.png)

![image](https://user-images.githubusercontent.com/7345587/221983099-e4c9f0eb-764f-4689-ae44-446e92b41276.png)

Fixing the excel may be enought

With a new excel I can provide you another build!
thx

**Comment by bovirus** [comment]
@Bazzu85
In this context "Warnings" in italian is "Avvisi" (not "Attenzione".
Then please send me a new Excel file and I will check.

**Comment by Bazzu85** [comment]
@bovirus 
You can use the last you have!

**Comment by bovirus** [comment]
New Excel file.

[2023_02_28_12_17.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/10858662/2023_02_28_12_17.xlsx)

**Comment by Bazzu85** [comment]
@bovirus 

here's: 
[MKVmergeBatcher 2.0.46.920.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/10860581/MKVmergeBatcher.2.0.46.920.zip)

**Comment by bovirus** [comment]
@Bazzu85 

[2023_02_28_12_17.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/10860980/2023_02_28_12_17.xlsx)

Program OK.
Just few string changed (I forgot to swap Move task up/on top)

Thanks.

**Comment by Bazzu85** [comment]
[MKVmergeBatcher 2.0.46.921.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/10861007/MKVmergeBatcher.2.0.46.921.zip)

If all is ok please close the issue and I'll put it in the release section!
thx

**Comment by bovirus** [comment]
@Bazzu85 

**Program is OK.**

Please take care about screenshot and strings.
For me the relative string in the context shouldn't end with "?"

![image](https://user-images.githubusercontent.com/1262554/222144651-8c1d8408-2558-4513-af22-b6a0d19501bb.png)

![image](https://user-images.githubusercontent.com/1262554/222145277-99ab528f-465f-4403-9f80-bfdb361f85fe.png)

**Language file update**

[2023_02_28_12_17.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/10861155/2023_02_28_12_17.xlsx)

**Popup after change GUI language**

If you can I suggest to add a popup when change GUI language that suggest to close and restarr program to take effect about new language file.
This to avoid that some part are not updated as language.

**Comment by Bazzu85** [comment]
> If you can I suggest to add a popup when change GUI language that suggest to close and restarr program to take effect about new language file.
> This to avoid that some part are not updated as language.

Theorically changing the language automatically update ALL strings.
Can you tell me what is not updating?

**Comment by bovirus** [comment]
@Bazzu85 

Are you right.
I didn't udnerstand why in the past (some version ago of this day) when I change GUI language some parts of Task list was not updated.
If I close and restart the application all messages are in right langiuage.
But now seems works fine.

**Comment by Bazzu85** [comment]
Good to hear that.

Here's last build: 
[MKVmergeBatcher 2.0.46.922.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/10861546/MKVmergeBatcher.2.0.46.922.zip)

**Comment by bovirus** [comment]
@Bazzu85 

All is OK: 

Issue closed. 
Many thanks.
