### ISSUE TITLE
Installation Instructions Needed

### ISSUE THREAD

**Issue by bitshifter52** [Bazzu85/MKVmergeBatcher#13]
I don't have a clue on how to install this under Linux (Ubuntu 22.04). The package seems like it might be very useful if only...

**Comment by Bazzu85** [comment]
@bitshifter52 Hi, unfortunately MkvmergeBatcher is available only for windows. You can try to prepare the wine environment and try to run the exe from there. Obviously you have the provide the mkvmerge.exe too.
Please let me know if with wine works so I can improve the initial readme
