### ISSUE TITLE
suggestion: Add the Option of "Finish the task, even if a track is missing"

### ISSUE THREAD

**Issue by SebastlAS** [Bazzu85/MKVmergeBatcher#14]
Firt of all, a huge tank you Bazzu85 for this tool, is very helpfull.

In my case there is an option tha i wish that you add it, if it´s possible.

the option of "Finish the task, even if a track is missing"

I have found some errors "open file error" in the task list, not finding a certain subtitle.
I made a model with:

Title.mp4
1 Video Tracks
2 Audio Tracks

Title.es.srt
Title.en.srt
Title.pt.srt
Title.es.forced.srt
Title.any.srt

but some titles have some of the tracks, but not all.

And on that occasion the error appears when executing the task

Once again, thank you for your time

**Comment by Bazzu85** [comment]
Hi, thanks for your feedback and suggestions!

Unfortunately the error is from mkvmerge.exe and cannot be avoided.

If I can suggest you a flow:
- give all the files to MkvmergeBatcher using the model with all external files
- when done delete/move away the original files that are correctly muxed
- give the remaining original files to MkvmergeBatcher with a more congruent model and repeat

Hope this can help.
