### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by publicdesert** [Bazzu85/MKVmergeBatcher#6]
Hey,
I just discovered this project and I think it's pretty neat. I'd like to contribute a German translation. Do I just need to translate the Excel sheet in /Translations and submit a PR or how is that handled in your project?

**Comment by Bazzu85** [comment]
Hi, I have to handle the German Language in the app and after that I have to make a new Excel sheet with the additional language. 
I'll do this ASAP..thx

**Comment by Bazzu85** [comment]
Added the German selection in https://github.com/Bazzu85/MKVmergeBatcher/commit/8ccced93fd437efcd6ac7f8ae876919d36af7de1

Please populate the last excel version here:
https://github.com/Bazzu85/MKVmergeBatcher/blob/master/Translactions/2022_05_24_17_39.xlsx

and attach here the new one! thx

**Comment by publicdesert** [comment]
I have attached the translated document here.
Some strings ended up being a bit longer than their equivalents in the other currently supported languages. If necessary, I can try to shorten those strings a bit but that might harm the comprehensibility somewhat.
[2022_05_24_17_39.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/8765982/2022_05_24_17_39.xlsx)

**Comment by publicdesert** [comment]
[2022_05_24_17_39.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/8770239/2022_05_24_17_39.xlsx)
I looked over it again a made a few small fixes. Everything should be good now.

**Comment by Bazzu85** [comment]
Added the translations and fixed the UI in https://github.com/Bazzu85/MKVmergeBatcher/commit/b464d48ea6020e1ec0cb4cda922c60b597a40c14

As you guessed every language as his own "dimensions". So after I import a new language I have to scan every window to check how is looking.

Please try the new release here:
https://github.com/Bazzu85/MKVmergeBatcher/releases/tag/2.0.42
and post If you see some UI glitchs...

thx

**Comment by publicdesert** [comment]
Thanks for the quick implementation. It looks very good. There were 2 or 3 strings that I've slightly mistranslated because I wasn't sure of the context. I've fixed those here: [2022_05_24_17_39 publicdesert.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/8778631/2022_05_24_17_39.publicdesert.xlsx)

There are 2 minor UI glitches related to the translation that I've noticed. It's nothing drastic though.

Firstly: The "Durchsuchen"/"Browse" buttons have the "n" at the end cut off. It should be "Durchsuchen", not "Durchsuche".
![browse_main_cutoff](https://user-images.githubusercontent.com/105128693/170480724-1713475c-8441-4674-be8d-b7d8e266fd52.png)
![browse_settings_cutoff](https://user-images.githubusercontent.com/105128693/170480733-1cac9656-ee1b-45d7-94fe-3fc0436be755.png)

Secondly: If you go to options > version, the text for the installed version is offset to the right and the colon is cut off.
![version_colon_cutoff](https://user-images.githubusercontent.com/105128693/170481208-96481eca-c864-4577-bbce-1a226da9a05e.png)

There seem to be 2 additional UI glitches that aren't directly related to the German translation but I thought I mention them:
Firstly: If you open the model window and hover over the move, create or delete buttons, the first section of the hover text will be in Italian even if you set your language to English, German or Spanish.
![italian_model](https://user-images.githubusercontent.com/105128693/170481805-42a036c9-4b4d-481f-b421-8d34d839fc25.png)

Secondly I noticed a glitch where if you keep changing the language and keep opening and closing the options window, the listed languages will start duplicating. Here's a small video to better understand what I mean.

https://user-images.githubusercontent.com/105128693/170483604-3e5a8bf8-a375-4650-a6f8-8105f3ab57f1.mp4

**Comment by Bazzu85** [comment]
> Thanks for the quick implementation. It looks very good. There were 2 or 3 strings that I've slightly mistranslated because I wasn't sure of the context. I've fixed those here: [2022_05_24_17_39 publicdesert.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/8778631/2022_05_24_17_39.publicdesert.xlsx)

Updated the strings with last version.

> Firstly: The "Durchsuchen"/"Browse" buttons have the "n" at the end cut off. It should be "Durchsuchen", not "Durchsuche".

Fixed in 09a7fb17feeeb0396574a461032fcdb0d347ae36. Wait for the next release

> Secondly: If you go to options > version, the text for the installed version is offset to the right and the colon is cut off.

Fixed in 09a7fb17feeeb0396574a461032fcdb0d347ae36. Wait for the next release

> Firstly: If you open the model window and hover over the move, create or delete buttons, the first section of the hover text will be in Italian even if you set your language to English, German or Spanish.

Fixed in 09a7fb17feeeb0396574a461032fcdb0d347ae36. Wait for the next release
The ToolTip title localization is a pain. So I removed it. The ToolTips contents on the other side are localized

> Secondly I noticed a glitch where if you keep changing the language and keep opening and closing the options window, the listed languages will start duplicating. Here's a small video to better understand what I mean.

Thx. I'm able to reproduce the bug. I'll try to fix it tomorrow.

In the next build I'm confident that all is fixed. Thanks

**Comment by Bazzu85** [comment]
@publicdesert I was waiting for a response about a message that I didn't send ..sorry

Check the last release with the last fixes.

If all is ok please close the issue!

**Comment by publicdesert** [comment]
@Bazzu85
Hey, I've tested the latest release. Everything I've mentioned is fixed.

I hate to say so but while running a larger job yesterday I've noticed a few more issues.

Firstly: When converting 10 or more files, the text in the bottom left of the queue window will overlap with the first progress bar. Unfortunately I forgot to take a proper screenshot, but here is the string that I mean:
![grafik](https://user-images.githubusercontent.com/105128693/170887897-18eb7b3b-8001-4787-850c-d267cf0bd24c.png)

Secondly: There's also a "Browse"/"Durchsuchen" button in the "Import Userdata" window where the "n" at the end is cut off.
![grafik](https://user-images.githubusercontent.com/105128693/170887723-ab9b418c-d082-4db9-bb56-690db17e8eb2.png)

Thirdly: These buttons both have the last words cut off. They should read "Vorlage speichern" and "Gespeicherte Vorlage laden":
![grafik](https://user-images.githubusercontent.com/105128693/170888259-112d8f12-03b8-45f7-8c15-dfe759a336ed.png)

I'm pretty sure I've cought everything this time. Thank you for your work!

**Comment by Bazzu85** [comment]
@publicdesert Ok, the most important thing is that this is only UX problems and not usage bugs. Tomorrow I'll fix all and I send the new release..

**Comment by Bazzu85** [comment]
> Unfortunately I forgot to take a proper screenshot, but here is the string that I mean:
> ![grafik](https://user-images.githubusercontent.com/105128693/170887897-18eb7b3b-8001-4787-850c-d267cf0bd24c.png)

Dont' worry, I understood the problem. 
Fixed in https://github.com/Bazzu85/MKVmergeBatcher/commit/64d9db756231ac96562edc22e670d2770357dd00

> Secondly: There's also a "Browse"/"Durchsuchen" button in the "Import Userdata" window where the "n" at the end is cut off.
> ![grafik](https://user-images.githubusercontent.com/105128693/170887723-ab9b418c-d082-4db9-bb56-690db17e8eb2.png)

Fixed in https://github.com/Bazzu85/MKVmergeBatcher/commit/64d9db756231ac96562edc22e670d2770357dd00

> Thirdly: These buttons both have the last words cut off. They should read "Vorlage speichern" and "Gespeicherte Vorlage laden":
> ![grafik](https://user-images.githubusercontent.com/105128693/170888259-112d8f12-03b8-45f7-8c15-dfe759a336ed.png)

Fixed in https://github.com/Bazzu85/MKVmergeBatcher/commit/64d9db756231ac96562edc22e670d2770357dd00

Please try this build:
[MKVmergeBatcher 2.0.43.873.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/8799634/MKVmergeBatcher.2.0.43.873.zip)

When all is ok I'll pubblish it.
thx for your time

**Comment by publicdesert** [comment]
Looks great, thank you very much! I'll close this issue then.
