### ISSUE TITLE
Translate MKVmergeBatcher in Russian

### ISSUE THREAD

**Issue by p1zrv** [Bazzu85/MKVmergeBatcher#7]
Hello. I want to translate MKVmergeBatcher in Russian. What do I have to do?

**Comment by Bazzu85** [comment]
@p1zrv Hi, thx to reach me out. I have to handle the russian language into the app and provide you an excel with the blank russian translation! Unfortunately I'm leaving my house for a week so I don't know if I can provide it to you in the short period!

**Comment by p1zrv** [comment]
> @p1zrv Hi, thx to reach me put. I have to handle the russian language into the app and provide you an excel with the blank russian translation! Unfortunately I'm leaving my house for a week so I don't know if I can provide it to you in the short period!

No problem, thanks for letting me know. I'll just wait for it.

**Comment by Bazzu85** [comment]
Hi @p1zrv, sorry for the delay.
I added the Russian language selection to the code and made a new excel. You can find here: https://github.com/Bazzu85/MKVmergeBatcher/blob/master/Translactions/2022_07_27_00_11.xlsx

Download it, populate the Russian column and attach the new file here.
After that I can try to import it into the project hoping there's no special characters problems!

ty

**Comment by p1zrv** [comment]
Guess it's done tho I'm not sure about some lines. Can't test it myself cause MKVmergeBatcher uses dlls for translations. Hope everything will be ok.
[2022_07_27_00_11.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/9214523/2022_07_27_00_11.xlsx)

**Comment by Bazzu85** [comment]
@p1zrv Don't worry. I'll update the app ASAP and attach a build for you to test the translation!

**Comment by Bazzu85** [comment]
Hi @p1zrv .
Can you please try this version?
[MKVmergeBatcher 2.0.44.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/9217180/MKVmergeBatcher.2.0.44.zip)

If you find bug or graphical glitchs please report here with a screenshot!  ty

**Comment by p1zrv** [comment]
@Bazzu85 Thanks.
[screenshots_ru_translation.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/9220415/screenshots_ru_translation.zip)
Untitled 01 and Untitled 04 - 93 and 99,85 lines respectively. I translated them but they don't seem to be used.
Untitled 06 (warning when you click on x after compiling model) and Untitled 07 (right click on model options in main menu)  - not sure if they can be translated cause there are no lines for them.
Untitled 02 (if open About) 03 (Models - Edit button) 05 (in Show Queue, Status) 08 (Options - Queue) - graphical glitchs (?)
Do I have to translate 260 and 266 lines? They are written as if they aren't used (fileNameWithoutExtension, fileFullPath)
Made some changes, is it possible to get new dll for this translation?
[2022_07_27_00_11.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/9220159/2022_07_27_00_11.xlsx)

**Comment by Bazzu85** [comment]
Hi,

I made the majority of the fix. 
I found some bugs and thx to your screens I fixed the translation on all languages (screens 1 and 4)
Some missing translation are based on your system UI language (screens 6 and 7) so I can't donanything.
About the screen 5 I don't know how to fix because this is a dynamic text placed on a grid table cell and usually the column width adapt by itself.
Screen 8 is not a glitch, the Russian text is long so the label is placed in two rows.

If you need to add other translation please start from this:
[2022_08_02_17_25.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/9243563/2022_08_02_17_25.xlsx)

Here's the last compiled version of the app: 
[MKVmergeBatcher 2.0.44.888.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/9243568/MKVmergeBatcher.2.0.44.888.zip)

Let me know if now can be ok!

**Comment by p1zrv** [comment]
@Bazzu85 Hello/
Thanks, fixed some lines in xlsx file - [2022_08_02_17_25.xlsx](https://github.com/Bazzu85/MKVmergeBatcher/files/9268104/2022_08_02_17_25.xlsx)
[screenshots_ru_translation 2.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/9267983/screenshots_ru_translation.2.zip)
01: View - Models - Add model (somehow it shifted a bit now).
02: Changed translation, needs to be fixed a little bit.
Guess translation is finished, everything seems to be ok.
+discord link needs to be updated cause it's invalid now (in app).

**Comment by Bazzu85** [comment]
@p1zrv Hi, here's a release with the last fixes:
[MKVmergeBatcher 2.0.44.890.zip](https://github.com/Bazzu85/MKVmergeBatcher/files/9290820/MKVmergeBatcher.2.0.44.890.zip)

Can you validate that's all ok? 
about the discord link, I tried right now and it's ok... idk sorry

**Comment by p1zrv** [comment]
@Bazzu85 
> about the discord link, I tried right now and it's ok... idk sorry

I mean in app discord link is expired. Link in app - https://discord.gg/ptZSVtAq (? - About - Discord server).
![image](https://user-images.githubusercontent.com/58609923/183702817-ba282214-7d5d-4002-bbbe-8456b4974d6a.png)

I suppose it should be changed to this link https://discord.gg/Eztf8tQWdt (link from README.md).
> Can you validate that's all ok?

Yeah, everything is ok.

**Comment by Bazzu85** [comment]
@p1zrv Sorry for the misunderstanding. Thx, I'll update it before the next release.

**Comment by Bazzu85** [comment]
Hi, @p1zrv here [https://github.com/Bazzu85/MKVmergeBatcher/releases/tag/2.0.44](url) 
you can find the last stable release with all fixes!
thx for you contribution!

**Comment by p1zrv** [comment]
@Bazzu85 Thanks!
